/*
  Copyright 2011 Dave Johnson

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/
package org.pantry.food.ui.dialog;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

import org.pantry.food.model.Volunteer;

/**
 *
 * @author Dave Johnson
 */
public class AddEditVolunteerDialog extends javax.swing.JDialog {
	
    private JButton btnCancel;
    private JButton btnOk;
    private JComboBox<String> cboType;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JLabel lblPhone;
    private JLabel lblName;
    private JLabel lblEmail;
    private JLabel lblType;
    private JLabel lblVolunteerId;
    private JTextField txtPhone;
    private JTextField txtName;
    private JTextField txtEmail;
    private JTextField txtVolunteerId;
    private JTextField txtNotes;

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	/** Creates new form AddEditCustomerDialog */
    public AddEditVolunteerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
    	
    	setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add or Edit Regular Volunteer"); 
        setName("Form");
        setSize(488,380);

        jPanel1 = new JPanel();
        jPanel1.setBounds(6, 6, 464, 265);
        jPanel1.setName("jPanel1");
      
        
        lblVolunteerId = new JLabel();
        lblVolunteerId.setBounds(30, 30, 81, 16);
        lblVolunteerId.setText("Volunteer Id"); 
        lblVolunteerId.setName("lblVolunteerId"); 
        
        
        txtVolunteerId = new JTextField();
        txtVolunteerId.setEditable(false);
        txtVolunteerId.setBounds(121, 24, 78, 28);
        txtVolunteerId.setHorizontalAlignment(SwingConstants.RIGHT);
        txtVolunteerId.setName("txtVolunteerId"); 
        txtVolunteerId.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
			public void focusGained(java.awt.event.FocusEvent evt) {
            }
        });
        
        lblEmail = new JLabel();
        lblEmail.setBounds(30, 155, 68, 16);
        lblEmail.setText("Email"); 
        lblEmail.setName("lblEmail"); 
        
        txtEmail = new JTextField();
        txtEmail.setHorizontalAlignment(SwingConstants.LEFT);
        txtEmail.setBounds(121, 149, 291, 28);
        txtEmail.setName("txtEmail"); 
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
			public void focusGained(java.awt.event.FocusEvent evt) {
            	txtEmail.selectAll();
            }
        });
        
        
        jPanel2 = new JPanel();
        jPanel2.setBounds(6, 283, 464, 56);
        jPanel2.setName("jPanel2"); 
        
        
        btnOk = new JButton();
        btnOk.setBounds(231, 6, 106, 36);
        btnOk.setIcon(new ImageIcon(AddEditVolunteerDialog.class.getResource("/org/pantry/food/resources/images/accept.png"))); 
        btnOk.setText("OK"); 
        btnOk.setName("btnOk"); 
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        
        btnCancel = new JButton();
        btnCancel.setBounds(349, 6, 102, 37);
        btnCancel.setIcon(new ImageIcon(AddEditVolunteerDialog.class.getResource("/org/pantry/food/resources/images/cancel.png"))); 
        btnCancel.setText("Cancel"); 
        btnCancel.setName("btnCancel"); 
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().setLayout(null);

        getContentPane().add(jPanel1);
        jPanel1.setLayout(null);
        jPanel1.add(lblVolunteerId);
        jPanel1.add(txtVolunteerId);
        
        
        lblType = new JLabel();
        lblType.setBounds(235, 30, 44, 16);
        lblType.setText("Type"); 
        lblType.setName("lblType"); 
        jPanel1.add(lblType);
        
        lblName = new JLabel();
        lblName.setBounds(30, 70, 62, 16);
        lblName.setText("Name"); 
        lblName.setName("lblName"); 
        jPanel1.add(lblName);
        
        txtName = new JTextField();
        txtName.setBounds(121, 64, 291, 28);
        txtName.setHorizontalAlignment(SwingConstants.LEFT);
        txtName.setToolTipText("");
        txtName.setName("txtName"); 
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
			public void focusGained(java.awt.event.FocusEvent evt) {
            	txtName.selectAll();
            }
        });
        jPanel1.add(txtName);
        
        cboType = new JComboBox<String>();
        cboType.setBounds(291, 26, 121, 27);
        cboType.setModel(new DefaultComboBoxModel<String>(new String[] {"Regular", "Student", "Special", "Other"}));
        cboType.setName("cboType"); 
        jPanel1.add(cboType);
        
        lblPhone = new JLabel();
        lblPhone.setBounds(30, 115, 81, 16);
        lblPhone.setText("Phone"); 
        lblPhone.setName("lblPhone"); 
        jPanel1.add(lblPhone);
        
        txtPhone = new JTextField();
        txtPhone.setBounds(121, 104, 291, 28);
        txtPhone.setHorizontalAlignment(SwingConstants.LEFT);
        txtPhone.setName("txtPhone"); 
        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
			public void focusGained(java.awt.event.FocusEvent evt) {
            	txtPhone.selectAll();
            }
        });
        jPanel1.add(txtPhone);
        jPanel1.add(lblEmail);
        jPanel1.add(txtEmail);
        
        JLabel lblNotes = new JLabel();
        lblNotes.setText("Notes");
        lblNotes.setName("lblNotes");
        lblNotes.setBounds(30, 198, 68, 16);
        jPanel1.add(lblNotes);
        
        txtNotes = new JTextField();
        txtNotes.setHorizontalAlignment(SwingConstants.LEFT);
        txtNotes.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusGained(FocusEvent arg0) {
        		txtNotes.selectAll();
        	}
        });
        txtNotes.setName("txtNotes");
        txtNotes.setBounds(121, 189, 291, 28);
        jPanel1.add(txtNotes);

        getContentPane().add(jPanel2);
        jPanel2.setLayout(null);
        jPanel2.add(btnOk);
        jPanel2.add(btnCancel);

    }


    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {

        if (validateForm()){
            this.OkCancel = true;
            generate();
            this.dispose();
        }

    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {

        this.OkCancel = false;
        this.volunteer = null;
        this.dispose();

    }

    private boolean OkCancel = false;
    public boolean getOkCancel(){return this.OkCancel;}

    private Volunteer volunteer = new Volunteer();

    public Volunteer getNewVolunteer(){return this.volunteer;}
    public void setNewVolunteer(Volunteer vol){
        this.volunteer = vol;
        setControlsFromPrevious();
    }

    private void setControlsFromPrevious(){
    	
        this.txtVolunteerId.setText("" + this.volunteer.getVolunteerId());
        this.cboType.setSelectedItem(this.volunteer.getType());
        this.txtName.setText(this.volunteer.getName());
        this.txtPhone.setText(this.volunteer.getPhone());
        this.txtEmail.setText(this.volunteer.getEmail());
        this.txtNotes.setText(this.volunteer.getNote());

    }

    private void generate(){

        this.volunteer.setVolunteerId(Integer.parseInt(this.txtVolunteerId.getText()));
        this.volunteer.setType(this.cboType.getSelectedItem().toString());
        this.volunteer.setName(this.txtName.getText());
        this.volunteer.setPhone(txtPhone.getText());
        this.volunteer.setEmail(txtEmail.getText());
        this.volunteer.setNote(txtNotes.getText());

    }

    private boolean validateForm(){

        if (this.txtVolunteerId.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(this,"Please select a person id.");
            return false;
        }

        if (this.txtName.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(this,"Please select a name.");
            return false;
        }

        /*
         * By request of Sue, she doesn't want phone numbers
        if (this.txtPhone.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(this,"Please enter the person's phone.");
            return false;
        }
        */


        return true;
    }


}// end of class
