/*
  Copyright 2011 Dave Johnson

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/
package org.pantry.food.ui.frame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JEditorPane;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JToolBar;
import javax.swing.SwingConstants;

import org.pantry.food.reports.IReportBase;
import org.pantry.food.ui.common.FormState;

/**
 *
 * @author Dave Johnson
 */
public class FrameReportViewer extends javax.swing.JInternalFrame {
	private final static Logger log = Logger.getLogger(FrameReportViewer.class.getName());

	private JButton btnPrint;
	private JButton btnSave;
	private JEditorPane editorPane;
	private JScrollPane jScrollPane1;
	private JToolBar jToolBar1;

	/**
	 * 
	 */
	private static final long serialVersionUID = -2746967929135530088L;

	/** Creates new form FrameReportViewer */
	public FrameReportViewer() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jToolBar1 = new JToolBar();
		btnPrint = new JButton();
		btnSave = new JButton();
		jScrollPane1 = new JScrollPane();
		editorPane = new JEditorPane();

		setClosable(true);
		setTitle("Report Viewer");
		setFrameIcon(
				new ImageIcon(FrameReportViewer.class.getResource("/org/pantry/food/resources/images/report.png")));
		setName("Form");
		addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
			public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
				formInternalFrameClosed(evt);
			}

			public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
			}
		});

		jToolBar1.setFloatable(false);
		jToolBar1.setRollover(true);
		jToolBar1.setName("jToolBar1");

		btnPrint.setIcon(
				new ImageIcon(FrameReportViewer.class.getResource("/org/pantry/food/resources/images/printer.png")));
		btnPrint.setText("Print");
		btnPrint.setFocusable(false);
		btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnPrint.setName("btnPrint");
		btnPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnPrint.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnPrintActionPerformed(evt);
			}
		});
		jToolBar1.add(btnPrint);

		btnSave.setIcon(new ImageIcon(
				FrameReportViewer.class.getResource("/org/pantry/food/resources/images/bullet_disk.png")));
		btnSave.setText("Save");
		btnSave.setFocusable(false);
		btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnSave.setName("btnSave");
		btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSaveActionPerformed(evt);
			}
		});
		jToolBar1.add(btnSave);

		getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

		btnPdf = new JButton();
		btnPdf.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				btnPdfActionPerformed(e);
			}
		});
		btnPdf.setIcon(new ImageIcon(
				FrameReportViewer.class.getResource("/org/pantry/food/resources/images/report_disk.png")));
		btnPdf.setVerticalTextPosition(SwingConstants.BOTTOM);
		btnPdf.setText("PDF");
		btnPdf.setName("btnSave");
		btnPdf.setHorizontalTextPosition(SwingConstants.CENTER);
		btnPdf.setFocusable(false);
		jToolBar1.add(btnPdf);

		jScrollPane1.setName("jScrollPane1");

		editorPane.setEditable(false);
		editorPane.setName("editorPane");
		jScrollPane1.setViewportView(editorPane);

		getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

		pack();
	}

	private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {
		print();
	}

	private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
		FormState.getInstance().setFormOpen(false);
	}

	private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
		save();
	}

	private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {
		savePdf();
	}

	private IReportBase reportBase;
	private JButton btnPdf;

	public void setDisplayFromFile(String path) {

	}

	public void setDisplayFromStringBuffer(StringBuffer buffer) {

		editorPane.setContentType("text/html");
		editorPane.setText(buffer.toString());
	}

	public void setDisplayFromIReport(IReportBase report) {
		reportBase = report;
		editorPane.setContentType("text/html");
//		editorPane.setText(report.getBuffer().toString());

	}

	private void print() {
		try {
			this.editorPane.print();
		} catch (PrinterException ex) {
			log.log(Level.SEVERE, null, ex);
		}

	}

	private void save() {
		try {
			String path = reportBase.savePdf();
			JOptionPane.showMessageDialog(this, "Report saved at:" + path);

		} catch (IOException ex) {
			log.log(Level.SEVERE, null, ex);
		}

	}

	private void savePdf() {
		try {
			String path = reportBase.savePdf();
			JOptionPane.showMessageDialog(this, "Report saved at:" + path);

		} catch (IOException ex) {
			Logger.getLogger(FrameReportViewer.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

}
